openapi: 3.0.3
info:
  title: Deep Learning API
  description: >-
    An API for accessing Deep Learning data
  version: 0.0.1
  contact:
    name: Sebastian
servers:
  - url: http://localhost:8080
paths:
  /validation/status:
    get:
      tags: 
        - Validation Pipeline
      responses:
        '200': 
          description: Status of all validation data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Status'
                  
  /validation/models:
    get:
      tags: 
        - Validation Pipeline
      responses:
        '200': 
          description: A list of available models
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Model'
                  
  /validation/batches:
    get:
      tags: 
      - Validation Pipeline
      responses:
        '200':
          description: A list of available batches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Batch'

  /validation/batches/{batch-name}/classes:
    get:
      tags: 
      - Validation Pipeline
      responses:
        '200':
          description: A list of all classes tested in a batch
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Class'
    parameters:
    - name: batch-name
      in: path
      description: Name of batch
      required: true
      schema:
        type: string
      style: simple 
                  
  /validation/models/{model-name}:
    get:
      tags: 
        - Validation Pipeline
      responses:
        '200':
          description: Meta data of a specific model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Model'
    parameters:
    - name: model-name
      in: path
      description: Name of model
      required: true
      schema:
        type: string
      style: simple 
      
  /validation/models/{model-name}/{batch-name}/result:
    get:
      tags: 
      - Validation Pipeline
      responses:
        '200':
          description: Result data of a model
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'
    parameters:
    - name: model-name
      in: path
      description: Name of model
      required: true
      schema:
        type: string
      style: simple
    - name: batch-name
      in: path
      description: Name of batch
      required: true
      schema:
        type: string
      style: simple

  /validation/models/{model-name}/{batch-name}/result/predictions:
    get:
      tags: 
      - Validation Pipeline
      responses:
        '200':
          description: Prediction data of a model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PredictionResult'
    parameters:
    - name: model-name
      in: path
      description: Name of model
      required: true
      schema:
        type: string
      style: simple
    - name: batch-name
      in: path
      description: Name of batch
      required: true
      schema:
        type: string
      style: simple
                  
  /validation/models/{model-name}/{batch-name}/result/ground-truth:
    get:
      tags: 
      - Validation Pipeline
      responses:
        '200':
          description: Ground truth data of a model
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GroundTruthResult'
    parameters:
    - name: model-name
      in: path
      description: Name of model
      required: true
      schema:
        type: string
      style: simple
    - name: batch-name
      in: path
      description: Name of batch
      required: true
      schema:
        type: string
      style: simple
      
components:
  schemas:
    Class:
      type: object
      properties:
        name:
          type: string
    Model:
      type: object
      properties:
        name:
          type: string
        time:
          type: string
    Status:
      type: object
      properties:
        warning:
          type: boolean
        message:
          type: string
    Batch:
      type: object
      properties:
        name:
          type: string
    PredictionResult:
      type: object
      properties:
        prediction:
          type: integer
          format: int32
    GroundTruthResult:
      type: object
      properties:
        ground_truth:
          type: integer
          format: int32
    ValidationResult:
      type: object
      properties:
        accuracy:
          type: integer
          format: int32
    
